apiVersion: apps/v1
kind: Deployment
metadata:
  name: cld-text
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cld-text
  template:
    metadata:
      labels:
        app: cld-text
    spec:
      containers:
        - name: cld-text
          image: tharunmedam/cld-text:latest
          imagePullPolicy: IfNotPresent
